{
 "title": "Flecs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flecs_world_tick_count[10s])",
     "legendFormat": "fps"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(flecs_table_entity_memory_used) + sum(flecs_table_component_memory_used) + sum(flecs_system_memory_used)"
    }
   ]
  },
  {
   "title": "Entity count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "flecs_world_entity_count" }
   ]
  },
  {
   "title": "Component count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "flecs_world_component_count" }
   ]
  },
  {
   "title": "Table count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "flecs_world_table_count" }
   ]
  },
  {
   "title": "Thread count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "flecs_world_thread_count" }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(flecs_table_entity_memory_allocd) + sum(flecs_table_component_memory_allocd) + sum(flecs_system_memory_used)"
    }
   ]
  },
  {
   "title": "System count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(count(flecs_system_time_total) by (system))"
    }
   ]
  },
  {
   "title": "Active system count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(flecs_system_time_total{active=\"true\"})"
    }
   ]
  },
  {
   "title": "Allocations / s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(flecs_alloc_count[10s])) + sum(rate(flecs_realloc_count[10s]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "dthms",
   "valueName": "avg",
   "targets": [
    { "expr": "flecs_world_time" }
   ]
  },
  {
   "title": "FPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(flecs_world_tick_count[10s])",
     "legendFormat": " fps"
    },
    { "expr": "flecs_world_target_fps", "legendFormat": "target" }
   ]
  },
  {
   "title": "Frame performance breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flecs_world_time_total[10s])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flecs_table_entity_memory_used)",
     "legendFormat": "Entities"
    },
    {
     "expr": "sum(flecs_table_component_memory_used)",
     "legendFormat": "Components"
    },
    { "expr": "sum(flecs_system_memory_used)", "legendFormat": "Systems" }
   ]
  },
  {
   "title": "Time spent by phase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flecs_system_time_total[10s])) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Time spent by system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flecs_system_time_total{hidden=\"false\"}[10s]) > 0",
     "legendFormat": "{{system}}"
    },
    {
     "expr": "sum(rate(flecs_system_time_total{hidden=\"true\"}[10s]) > 0)",
     "legendFormat": "[hidden systems]"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(flecs_alloc_count[10s])", "legendFormat": "{{kind}}" },
    { "expr": "rate(flecs_realloc_count[10s])", "legendFormat": "realloc" },
    { "expr": "rate(flecs_free_count[10s])", "legendFormat": "free" }
   ]
  }
 ]
}