/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef ECS_PROMETHEUS_EXPORTER_BAKE_CONFIG_H
#define ECS_PROMETHEUS_EXPORTER_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_systems_civetweb.h>
#include <flecs_systems_prometheus.h>

/* Headers of private dependencies */
#ifdef ECS_PROMETHEUS_EXPORTER_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef ECS_PROMETHEUS_EXPORTER_STATIC
  #if ECS_PROMETHEUS_EXPORTER_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define ECS_PROMETHEUS_EXPORTER_EXPORT __declspec(dllexport)
  #elif ECS_PROMETHEUS_EXPORTER_IMPL
    #define ECS_PROMETHEUS_EXPORTER_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define ECS_PROMETHEUS_EXPORTER_EXPORT __declspec(dllimport)
  #else
    #define ECS_PROMETHEUS_EXPORTER_EXPORT
  #endif
#else
  #define ECS_PROMETHEUS_EXPORTER_EXPORT
#endif

#endif

